<?php
/**
 * @var Extait\Articles\Block\Article\RelatedProducts $block
 */
?>
<?php $products = $block->getRelatedProducts(); ?>
<?php if ($products) : ?>
    <div class="block related" data-limit="0" data-shuffle="0">
        <div class="block-title title">
            <strong id="block-related-heading" role="heading" aria-level="2">Related Products</strong>
        </div>
        <div class="block-content content" aria-labelledby="block-related-heading">
            <div class="products wrapper grid products-grid product-related">
                <ol class="products list items product-items">
                    <?php foreach ($products as $product) : ?>
                        <?php $href = $product->getProductUrl(); ?>
                        <?php $src = $block->getImageUrl($product); ?>
                        <?php $name = $product->getName(); ?>
                        <?php if ($href) : ?>
                            <li class="item product product-item" style="">
                                <div class="product-item-info related-available">
                                    <a class="product photo product-item-photo" href="<?= $href; ?>">
                                        <?php if ($src && $name) : ?>
                                            <span class="product-image-container" style="width:152px;">
                                                <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                                    <img class="product-image-photo" src="<?= $src; ?>" alt="Image" width="152" height="190">
                                                </span>
                                            </span>
                                    </a>
                                    <div class="product details product-item-details">
                                        <strong class="product name product-item-name">
                                            <a class="product-item-link" title="<?= $name; ?>" href="<?= $href; ?>"><?= $name; ?></a>
                                        </strong>
                                        <div class="price-box price-final_price" data-role="priceBox" data-product-id="3" data-price-box="product-id-3">
                                            <span class="price-container price-final_price tax weee">
                                                <span id="product-price-3" class="price-wrapper " data-price-amount="38" data-price-type="finalPrice">
                                                    <span class="price"><?= $block->getFormattedPrice($product); ?></span>
                                                </span>
                                            </span>
                                        </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
    </div>
<?php endif; ?>
